---
- name: Check if vsftpd is installed
  ansible.builtin.command: which vsftpd
  register: compliance_ftp_check
  changed_when: false
  failed_when: false

- name: Set FTP compliance
  ansible.builtin.set_fact:
    compliance_ftp_compliant: "{{ compliance_ftp_check.rc != 0 }}"
