---
- name: Check PermitRootLogin
  ansible.builtin.command: grep -i "PermitRootLogin" /etc/ssh/sshd_config
  register: compliance_root_login_check
  changed_when: false
  failed_when: false

- name: Set SSH root login compliance
  ansible.builtin.set_fact:
    compliance_ssh_root_compliant: >-
      {{ 'yes' not in compliance_root_login_check.stdout | lower
         if not ssh.permit_root_login
         else 'yes' in compliance_root_login_check.stdout | lower }}

- name: Check SSH Protocol
  ansible.builtin.command: grep -i "Protocol" /etc/ssh/sshd_config
  register: compliance_protocol_check
  changed_when: false
  failed_when: false

- name: Set SSH protocol compliance
  ansible.builtin.set_fact:
    compliance_ssh_protocol_compliant: >-
      {{ compliance_protocol_check.stdout | regex_search('Protocol\\s+' + ssh.protocol_version | string) is not none }}
