---
- name: Check SSH configuration
  ansible.builtin.include_tasks: check_ssh.yml

- name: Check NTP configuration
  ansible.builtin.include_tasks: check_ntp.yml

- name: Check security settings
  ansible.builtin.include_tasks: check_security.yml

- name: Check logging configuration
  ansible.builtin.include_tasks: check_logging.yml

- name: Check banner configuration
  ansible.builtin.include_tasks: check_banner.yml

- name: Check ACL configuration
  ansible.builtin.include_tasks: check_acl.yml
